apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "harvester-node-disk-manager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "harvester-node-disk-manager.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harvester-node-disk-manager.name" . }}
rules:
  - apiGroups: [ "harvesterhci.io" ]
    resources: [ "blockdevices", "lvmvolumegroups", "lvmvolumegroups/status" ]
    verbs: [ "*" ]
  - apiGroups: [ "longhorn.io" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "events" ]
    verbs: [ "get", "watch", "list", "update", "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "harvester-node-disk-manager.name" . }}
  labels:
  {{- include "harvester-node-disk-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harvester-node-disk-manager.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "harvester-node-disk-manager.name" . }}
    namespace: {{ .Release.Namespace }}
