#!/bin/bash
set -e

cd $(dirname $0)/..

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi
LINKFLAGS="-X github.com/rancher/node-disk-manager/pkg/version.Version=$VERSION"
LINKFLAGS="-X github.com/rancher/node-disk-manager/pkg/version.GitCommit=$COMMIT $LINKFLAGS"
GOOS=linux CGO_ENABLED=0 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/node-disk-manager

scp ./bin/node-disk-manager rancher@172.16.4.3:/home/rancher
