#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

IMAGE=${REPO}/node-disk-manager:${TAG}
if [[ -n ${BUILD_FOR_CI} ]]; then
    IMAGE=ttl.sh/node-disk-manager-${TAG}:1h
fi
DOCKERFILE=package/Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

buildx build --load -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
if [[ -n ${BUILD_FOR_CI} ]]; then
    docker push ${IMAGE}
    echo ${IMAGE} pushed
fi
