# syntax=docker/dockerfile:1.7.0

FROM registry.suse.com/bci/bci-base:15.6

ARG TARGETPLATFORM

RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
    exit 1; \
    fi

ENV ARCH=${TARGETPLATFORM#linux/}

COPY bin/node-disk-manager-webhook-${ARCH} /usr/bin/node-disk-manager-webhook
CMD ["node-disk-manager-webhook"]
